# Devarch Hyprpaper Configuration

preload = /usr/share/backgrounds/devarch/default.jpg

wallpaper = ,/usr/share/backgrounds/devarch/default.jpg

# Unload unused wallpapers to save memory
unload = 30
